export PROJECT = external-interrupts
export BOARD ?= msba2
include ../Makefile.applications_common

# lpc2387 based boards:
export BOARD_WHITELIST = msba2 pttu avsextrem

USEMODULE += gpioint

include $(RIOTBASE)/Makefile.include
