export PROJECT = test_crypto
include ../Makefile.applications_common

# list here all modules that are used in your project
USEMODULE += posix
USEMODULE += uart0
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += auto_init
USEMODULE += crypto_3des
USEMODULE += crypto_aes
USEMODULE += crypto_rc5
USEMODULE += crypto_skipjack
USEMODULE += crypto_twofish
USEMODULE += crypto_sha256

include $(RIOTBASE)/Makefile.include
