export PROJECT = test_ltc4150
include ../Makefile.applications_common

export BOARD_WHITELIST = msba2 pttu native avsextrem

USEMODULE += auto_init
USEMODULE += ltc4150

include $(RIOTBASE)/Makefile.include
