export PROJECT = test_ltc4150
export BOARD ?= native
export RIOTBASE ?= $(CURDIR)/../../RIOT
export QUIET ?= 1

export BOARD_WHITELIST = msba2 pttu native avsextrem

USEMODULE += auto_init
USEMODULE += ltc4150

include $(RIOTBASE)/Makefile.include
