export PROJECT = test_net_if
include ../Makefile.applications_common

BOARD_WHITELIST := telosb z1 wsn430-v1_4 
BOARD_BLACKLIST :=  

USEMODULE += auto_init
USEMODULE += transceiver
USEMODULE += cc2420

include $(RIOTBASE)/Makefile.include
